from typing import Literal, TypeAlias

MT5Code: TypeAlias = Literal[
    "MT5_INITIALIZE_OK",
    "MT5_SYMBOLS_GET_OK",
    "MT5_RATES_GET_OK",
    "MT5_INITIALIZE_FAILED",
    "MT5_SYMBOLS_GET_FAILED",
    "MT5_RATES_GET_FAILED",
    "MT5_LOGIN_ENV_INVALID",
]

MT5_INITIALIZE_OK: MT5Code = "MT5_INITIALIZE_OK"
MT5_SYMBOLS_GET_OK: MT5Code = "MT5_SYMBOLS_GET_OK"
MT5_RATES_GET_OK: MT5Code = "MT5_RATES_GET_OK"
MT5_INITIALIZE_FAILED: MT5Code = "MT5_INITIALIZE_FAILED"
MT5_SYMBOLS_GET_FAILED: MT5Code = "MT5_SYMBOLS_GET_FAILED"
MT5_RATES_GET_FAILED: MT5Code = "MT5_RATES_GET_FAILED"
MT5_LOGIN_ENV_INVALID: MT5Code = "MT5_LOGIN_ENV_INVALID"
